import type { StoryChapter, StoryWaypoint } from '../types/game';

export const STORY_CHAPTERS: StoryChapter[] = [
  {
    id: 'story_1',
    chapterNumber: 1,
    title: 'The Two Travelers',
    subtitle: 'Two paths across the same forest',
    content: `Long ago, two travelers walked these woods. One always walked during sunrise; the other always walked after sunset. Because of that... they almost never met. Yet every single day, they unknowingly crossed the same forest paths. One loved leaving little things behind—a feather, a drawing, a strange flower—with a note saying, "Someone might smile because of this." The other found them every morning, and began looking forward to tomorrow.`,
    requiredFireflies: 0,
    unlocked: true,
  },
  {
    id: 'story_2',
    chapterNumber: 2,
    title: 'Traces in the Dew',
    subtitle: 'Small surprises left behind',
    content: `As years passed, the forest filled with tiny memories. Whenever a firefly landed nearby, it replayed a forgotten moment—not a grand event, but someone laughing, someone losing a game, someone asking a silly question, someone saying, "There's always tomorrow." Neither traveler ever admitted they were searching for the other. They simply kept walking, leaving traces, finding them, and walking again.`,
    requiredFireflies: 6,
    unlocked: false,
  },
  {
    id: 'story_3',
    chapterNumber: 3,
    title: 'The Waiting Bench',
    subtitle: 'Cancelled calls and quiet rain',
    content: `Under the shelter of the rain canopy sits an old wooden bench where someone once waited during quiet, rainy afternoons. When calls were cancelled or plans delayed, they sat watching water ripples pool upon the pine needles. "There's always tomorrow," a note carved under the armrest whispers. "The rain doesn't rush, yet it fills the whole forest."`,
    requiredFireflies: 14,
    unlocked: false,
  },
  {
    id: 'story_4',
    chapterNumber: 4,
    title: 'Whispers & Cauliflowers',
    subtitle: 'The joke that grew into a flower',
    content: `Deep in the central glade stands the ancient Whisper Tree. Carved into its bark among unfinished notebook sentences is a drawing of a cauliflower disguised as a rare flower—an inside joke shared between two people who spoke a language only they understood. "Some thoughts don't need explaining," the bark remembers. "They just stay."`,
    requiredFireflies: 22,
    unlocked: false,
  },
  {
    id: 'story_5',
    chapterNumber: 5,
    title: 'Coffee Cups & Arcade Tokens',
    subtitle: 'Jokes, tally marks, and planned games',
    content: `Near the abandoned coffee kiosk rests a ceramic mug with tally marks for unpaid coffees, alongside a shiny brass token from a planned arcade game. "Coffee first, everything else later," the counter note reads. "Someone still owes someone coffee... maybe when the arcade machine is fixed."`,
    requiredFireflies: 32,
    unlocked: false,
  },
  {
    id: 'story_6',
    chapterNumber: 6,
    title: 'The Football in the Grass',
    subtitle: 'Memories resting among mossy roots',
    content: `In the hollow roots near the starlight lake rests a scuffed leather football and a notebook with half-written sentences. Without realizing it, their separate walks had woven a single shared story. But one day, the fireflies began disappearing, and the diary recording every tiny moment scattered into loose pages across the forest.`,
    requiredFireflies: 42,
    unlocked: false,
  },
  {
    id: 'story_7',
    chapterNumber: 7,
    title: 'The Missing Page',
    subtitle: 'The last page at the station campfire',
    content: `You reach the campfire by the old train tracks. As the scattered pages assemble into the complete diary, the forest slowly begins to glow again and the fireflies return. One missing page remains—the very last page. When you open it, there is no grand confession, only this: "Maybe we never walked together. Maybe life kept sending us on different roads. But somehow... every path I walked had signs that you had been there first."`,
    requiredFireflies: 48,
    unlocked: false,
  },
];

export const STORY_WAYPOINTS: StoryWaypoint[] = [
  {
    id: 'waypoint_1',
    chapterNumber: 1,
    title: 'The Scattered Diary & First Sparkle',
    subtitle: 'Tagline: "Some people stay inside the places they touched."',
    locationName: 'Central Glade Path',
    x: 3000,
    y: 3000,
    speakerName: 'The Forest Spirit',
    speakerAvatar: 'evelyn',
    zoneId: 'central_glade',
    completed: false,
    dialogText: `You awaken as a small glowing spirit at the edge of the forest twilight. In your hand is an old iron lantern, and scattered on the moss are loose pages of a forgotten diary.

"Long ago, two travelers crossed this forest—one at sunrise, one at sunset. They almost never met, but left tiny traces for each other. Now the fireflies are fading. Gather every page before the last light dims."`,
  },
  {
    id: 'waypoint_2',
    chapterNumber: 2,
    title: 'Traces in the Dew',
    subtitle: 'Chapter 2: Small Surprises Left Behind',
    locationName: 'Flower Meadow Slope',
    x: 1400,
    y: 3100,
    speakerName: 'Sunrise Traveler Note',
    speakerAvatar: 'tree',
    zoneId: 'meadow',
    completed: false,
    dialogText: `Tucked beneath a blooming wildflower is a faded paper note:

"One traveler loved leaving little things behind—a feather, a drawing, a strange flower. 'Someone might smile because of this.' The other found them every morning, and began looking forward to tomorrow."`,
  },
  {
    id: 'waypoint_3',
    chapterNumber: 3,
    title: 'The Waiting Bench',
    subtitle: 'Chapter 3: Cancelled Calls & Rain Shelters',
    locationName: 'Rain Canopy Shelter',
    x: 1400,
    y: 1200,
    speakerName: 'Rain Shelter Bench',
    speakerAvatar: 'evelyn',
    zoneId: 'rain_bench',
    completed: false,
    dialogText: `You find a secluded wooden bench under evergreen canopy as soft rain patters around you. Carved into the armrest is a short message:

"When calls were cancelled and plans delayed, someone sat here watching water ripples. 'There's always tomorrow.' The rain doesn't rush, yet it fills the whole forest."`,
  },
  {
    id: 'waypoint_4',
    chapterNumber: 4,
    title: 'Whispers & Cauliflowers',
    subtitle: 'Chapter 4: The Flower Joke & Unfinished Sentences',
    locationName: 'Whisper Tree Glade',
    x: 3000,
    y: 1100,
    speakerName: 'The Whisper Tree',
    speakerAvatar: 'tree',
    zoneId: 'whisper_tree',
    completed: false,
    dialogText: `The ancient Whisper Tree glows with luminescent violet spores. Carved into its bark is a sketch of a cauliflower labeled "Rare Flower" and unfinished notebook sentences.

"Some thoughts don't need explaining to the world. They just stay inside the bark where someone left them."`,
  },
  {
    id: 'waypoint_5',
    chapterNumber: 5,
    title: 'Coffee Cups & Arcade Tokens',
    subtitle: 'Chapter 5: Tally Marks & Planned Games',
    locationName: 'Coffee Corner Kiosk',
    x: 4400,
    y: 3100,
    speakerName: 'Abandoned Kiosk Counter',
    speakerAvatar: 'kiosk',
    zoneId: 'coffee_corner',
    completed: false,
    dialogText: `On the counter of the abandoned coffee kiosk rests a ceramic mug marked with tally marks, and a brass token from a 90s arcade machine.

"Someone still owes someone coffee... maybe when the arcade machine is fixed. Coffee first. Everything else later."`,
  },
  {
    id: 'waypoint_6',
    chapterNumber: 6,
    title: 'The Football in the Grass',
    subtitle: 'Chapter 6: Memory Hollow Keepsakes',
    locationName: 'Memory Hollow Roots',
    x: 4600,
    y: 4800,
    speakerName: 'Memory Hollow Trunk',
    speakerAvatar: 'cat',
    zoneId: 'memory_hollow',
    completed: false,
    dialogText: `Nestled in mossy tree roots is a scuffed leather football and a notebook page with half-finished sentences.

"Without realizing it, their separate daily walks had woven a single shared story. But when the diary scattered into loose pages, the forest began to forget..."`,
  },
  {
    id: 'waypoint_7',
    chapterNumber: 7,
    title: 'The Missing Page & The Campfire',
    subtitle: 'Chapter 7: The Final Destination',
    locationName: 'Old Train Station Campfire',
    x: 1500,
    y: 5100,
    speakerName: 'The Final Diary Page',
    speakerAvatar: 'evelyn',
    zoneId: 'train_station',
    completed: false,
    dialogText: `You arrive at the crackling campfire by the rustic train platform. The scattered pages bind together, leaving only the very last page:

"Maybe we never walked together. Maybe life kept sending us on different roads. But somehow... every path I walked had signs that you had been there first."`,
  },
];
