import type { StoryChapter, StoryWaypoint } from '../types/game';

export const STORY_CHAPTERS: StoryChapter[] = [
  {
    id: 'story_1',
    chapterNumber: 1,
    title: 'The Firefly Diary',
    subtitle: 'The forest born from tiny memories',
    content: `Long ago, this forest didn't exist. It was created by a single diary. The diary belonged to someone who wrote down whenever something made them smile—tiny moments like someone asking if they had eaten, someone losing a game, someone saying, "There's always tomorrow." Every memory became a firefly. But life became louder. Conversations became shorter. "Tomorrow" quietly replaced "Today." The fireflies began fading, and the diary scattered. Your job isn't saving the forest. Your job is remembering.`,
    requiredFireflies: 0,
    unlocked: true,
  },
  {
    id: 'story_2',
    chapterNumber: 2,
    title: 'Memory 1: Coffee',
    subtitle: 'One coffee became two',
    content: `One coffee became two. Then four. Then somehow... nobody remembered who owed whom anymore.`,
    requiredFireflies: 5,
    unlocked: false,
  },
  {
    id: 'story_3',
    chapterNumber: 3,
    title: 'Memory 2: The Arcade',
    subtitle: 'The high score',
    content: `The high score was never important. Laughing because somebody cheated was.`,
    requiredFireflies: 12,
    unlocked: false,
  },
  {
    id: 'story_4',
    chapterNumber: 4,
    title: 'Memory 3: The Football',
    subtitle: 'Practice finished',
    content: `Practice finished. Boots removed. Somebody was still waiting.`,
    requiredFireflies: 20,
    unlocked: false,
  },
  {
    id: 'story_5',
    chapterNumber: 5,
    title: 'Memory 4: The Cauliflower',
    subtitle: 'A flower without petals',
    content: `Not every flower needs petals. 😂`,
    requiredFireflies: 28,
    unlocked: false,
  },
  {
    id: 'story_6',
    chapterNumber: 6,
    title: 'Memory 5: The Notebook',
    subtitle: 'One single sentence',
    content: `"Let's learn together."`,
    requiredFireflies: 36,
    unlocked: false,
  },
  {
    id: 'story_7',
    chapterNumber: 7,
    title: 'Memory 6: The Bench',
    subtitle: 'Today\'s slot expired',
    content: `Today's slot expired. There's always tomorrow.`,
    requiredFireflies: 44,
    unlocked: false,
  },
  {
    id: 'story_8',
    chapterNumber: 8,
    title: 'Memory 7 & 8: Chocolate & The Dream',
    subtitle: 'The same book',
    content: `Someone chose only chocolate. Someone forced them to choose a book too. Somehow... they both picked the same one. Some stories are easier to tell in dreams.`,
    requiredFireflies: 52,
    unlocked: false,
  },
  {
    id: 'story_9',
    chapterNumber: 9,
    title: 'Memory 9 & 10: The Glowing Pen',
    subtitle: 'Whose pen it really was',
    content: `Nobody knew whose pen it really was. 😂 Some stories are easier to tell under starlight.`,
    requiredFireflies: 60,
    unlocked: false,
  },
  {
    id: 'story_10',
    chapterNumber: 10,
    title: 'The Spaces Between Chapters',
    subtitle: 'The final campfire page',
    content: `Some people become your biggest chapter. Some become the spaces between chapters. Coffee. Books. Waiting. Learning. Stupid jokes. Fireflies. Maybe memories don't become important because they're big. Maybe they become important because someone remembers them.`,
    requiredFireflies: 70,
    unlocked: false,
  },
];

export const STORY_WAYPOINTS: StoryWaypoint[] = [
  {
    id: 'waypoint_1',
    chapterNumber: 1,
    title: 'The Firefly Diary',
    subtitle: 'Chapter 1: The Forest Spirit Awakens',
    locationName: 'Central Glade Path',
    x: 5000,
    y: 5000,
    speakerName: 'The Forest Spirit',
    speakerAvatar: 'evelyn',
    zoneId: 'central_glade',
    completed: false,
    dialogText: `You awaken in the twilight forest. Long ago, this place didn't exist—it was created by a single diary. Whenever something made someone smile, they wrote it down. Every memory became a firefly.

Then life became louder. Conversations became shorter. "Tomorrow" quietly replaced "Today." The fireflies began fading. Your job isn't saving the forest. Your job is remembering.`,
  },
  {
    id: 'waypoint_2',
    chapterNumber: 2,
    title: 'Memory 1: Coffee',
    subtitle: 'Chapter 2: Coffee Corner',
    locationName: 'Coffee Corner Kiosk',
    x: 8000,
    y: 4800,
    speakerName: 'Ceramic Mug',
    speakerAvatar: 'kiosk',
    zoneId: 'coffee_corner',
    completed: false,
    dialogText: `One coffee became two. Then four. Then somehow... nobody remembered who owed whom anymore.`,
  },
  {
    id: 'waypoint_3',
    chapterNumber: 3,
    title: 'Memory 2: The Arcade',
    subtitle: 'Chapter 3: Retro Arcade Shrine',
    locationName: 'Arcade Ruins Shrine',
    x: 2000,
    y: 1500,
    speakerName: 'Arcade Token Slot',
    speakerAvatar: 'kiosk',
    zoneId: 'arcade_ruins',
    completed: false,
    dialogText: `The high score was never important. Laughing because somebody cheated was.`,
  },
  {
    id: 'waypoint_4',
    chapterNumber: 4,
    title: 'Memory 3: The Football',
    subtitle: 'Chapter 4: Memory Hollow Roots',
    locationName: 'Memory Hollow Roots',
    x: 8000,
    y: 7800,
    speakerName: 'Scuffed Leather Football',
    speakerAvatar: 'cat',
    zoneId: 'memory_hollow',
    completed: false,
    dialogText: `Practice finished. Boots removed. Somebody was still waiting.`,
  },
  {
    id: 'waypoint_5',
    chapterNumber: 5,
    title: 'Memory 4: The Cauliflower',
    subtitle: 'Chapter 5: Cauliflower Ridge',
    locationName: 'Cauliflower Ridge Bench',
    x: 2000,
    y: 8200,
    speakerName: 'Golden Bloom',
    speakerAvatar: 'tree',
    zoneId: 'cauliflower_ridge',
    completed: false,
    dialogText: `Not every flower needs petals. 😂`,
  },
  {
    id: 'waypoint_6',
    chapterNumber: 6,
    title: 'Memory 5: The Notebook',
    subtitle: 'Chapter 6: Flower Meadow Slope',
    locationName: 'Flower Meadow Slope',
    x: 2000,
    y: 4800,
    speakerName: 'Open Notebook',
    speakerAvatar: 'tree',
    zoneId: 'meadow',
    completed: false,
    dialogText: `"Let's learn together."`,
  },
  {
    id: 'waypoint_7',
    chapterNumber: 7,
    title: 'Memory 6: The Bench',
    subtitle: 'Chapter 7: Rain Canopy Shelter',
    locationName: 'Rain Canopy Shelter',
    x: 2000,
    y: 2800,
    speakerName: 'Rain Bench',
    speakerAvatar: 'evelyn',
    zoneId: 'rain_bench',
    completed: false,
    dialogText: `Today's slot expired. There's always tomorrow.`,
  },
  {
    id: 'waypoint_8',
    chapterNumber: 8,
    title: 'Memory 7 & 8: Chocolate & The Dream',
    subtitle: 'Chapter 8: Starlight Observatory',
    locationName: 'Observatory Tower',
    x: 5000,
    y: 8500,
    speakerName: 'The Same Book',
    speakerAvatar: 'tree',
    zoneId: 'observatory',
    completed: false,
    dialogText: `Someone chose only chocolate. Someone forced them to choose a book too. Somehow... they both picked the same one. Some stories are easier to tell in dreams.`,
  },
  {
    id: 'waypoint_9',
    chapterNumber: 9,
    title: 'Memory 9: The Glowing Pen',
    subtitle: 'Chapter 9: Whisper Tree Glade',
    locationName: 'Whisper Tree Glade',
    x: 5000,
    y: 2000,
    speakerName: 'The Whisper Tree',
    speakerAvatar: 'tree',
    zoneId: 'whisper_tree',
    completed: false,
    dialogText: `Nobody knew whose pen it really was. 😂

"Some words are not ready for another heart. Leave them here. The forest keeps promises."`,
  },
  {
    id: 'waypoint_10',
    chapterNumber: 10,
    title: 'The Spaces Between Chapters',
    subtitle: 'Chapter 10: Station Campfire',
    locationName: 'Old Train Station Campfire',
    x: 2000,
    y: 9200,
    speakerName: 'The Final Page',
    speakerAvatar: 'evelyn',
    zoneId: 'train_station',
    completed: false,
    dialogText: `Some people become your biggest chapter.
Some become the spaces between chapters.

Coffee.
Books.
Waiting.
Learning.
Stupid jokes.
Fireflies.

Maybe memories don't become important because they're big.
Maybe they become important because someone remembers them.`,
  },
];
