import type {
  CassetteTapeEntity,
  CoffeeBeanEntity,
  EasterEggEntity,
  FireflyEntity,
  InteractivePoint,
  LetterEntity,
  ZoneInfo,
} from '../types/game';

// 8 Open World Biomes across 6000px × 6000px Map Grid
export const ZONES: ZoneInfo[] = [
  {
    id: 'central_glade',
    name: 'Central Glade',
    minX: 2400,
    maxX: 3600,
    minY: 2400,
    maxY: 3600,
    description: 'A serene opening path at the heart of the forest surrounded by soft twilight.',
    ambientSound: 'forest',
  },
  {
    id: 'meadow',
    name: 'Flower Meadow & Windmill Hill',
    minX: 400,
    maxX: 2400,
    minY: 2400,
    maxY: 4200,
    description: 'Fields of glowing lavender, gold wildflowers, and gentle hilltop breezes.',
    ambientSound: 'wind',
  },
  {
    id: 'rain_bench',
    name: 'Rain Canopy & Shelter',
    minX: 400,
    maxX: 2400,
    minY: 400,
    maxY: 2400,
    description: 'A secluded wooden bench sheltered under evergreen leaves with peaceful rain.',
    ambientSound: 'rain',
  },
  {
    id: 'whisper_tree',
    name: 'Whisper Tree Glade',
    minX: 2400,
    maxX: 3600,
    minY: 400,
    maxY: 2400,
    description: 'The ancient glowing heart of the forest. The tree listens closely, but never answers.',
    ambientSound: 'wind',
  },
  {
    id: 'lake',
    name: 'Firefly Lake & Starlight Pier',
    minX: 3600,
    maxX: 5600,
    minY: 400,
    maxY: 2400,
    description: 'Starlight and fireflies reflect off calm lake waters. Smooth stones line the shore.',
    ambientSound: 'stream',
  },
  {
    id: 'coffee_corner',
    name: 'Coffee Corner Kiosk',
    minX: 3600,
    maxX: 5600,
    minY: 2400,
    maxY: 4200,
    description: 'A small abandoned coffee stand left in the forest. Warm aromas linger.',
    ambientSound: 'forest',
  },
  {
    id: 'memory_hollow',
    name: 'Memory Hollow Roots',
    minX: 3600,
    maxX: 5600,
    minY: 4200,
    maxY: 5600,
    description: 'Forgotten keepsakes rest among mossy roots: letters, old photos, and cassette tapes.',
    ambientSound: 'forest',
  },
  {
    id: 'train_station',
    name: 'Old Train Station',
    minX: 400,
    maxX: 2400,
    minY: 4200,
    maxY: 5600,
    description: 'A rustic abandoned station platform with a small crackling campfire.',
    ambientSound: 'station',
  },
];

// 1. Generate 50 Glowing Fireflies scattered in 6000x6000px space
export function generateFireflies(): FireflyEntity[] {
  const fireflies: FireflyEntity[] = [];
  const colors = ['#fef08a', '#fde047', '#fed7aa', '#ddd6fe', '#bae6fd'];

  for (let i = 1; i <= 50; i++) {
    const angle = i * 0.42;
    const r = 350 + i * 95;
    const baseX = 3000 + Math.cos(angle) * r;
    const baseY = 3000 + Math.sin(angle) * r;

    const zone = ZONES.find(
      (z) => baseX >= z.minX && baseX <= z.maxX && baseY >= z.minY && baseY <= z.maxY
    ) || ZONES[0];

    fireflies.push({
      id: `firefly_${i}`,
      x: Math.max(200, Math.min(5800, baseX)),
      y: Math.max(200, Math.min(5800, baseY)),
      baseX: Math.max(200, Math.min(5800, baseX)),
      baseY: Math.max(200, Math.min(5800, baseY)),
      collected: false,
      color: colors[i % colors.length],
      radius: 4.0 + (i % 3),
      pulsePhase: Math.random() * Math.PI * 2,
      floatAngle: Math.random() * Math.PI * 2,
      speed: 0.5 + Math.random() * 0.8,
      zoneId: zone.id,
    });
  }

  return fireflies;
}

// 2. 15 Micro-Letters scattered across 6000x6000px map
export const INITIAL_LETTERS: LetterEntity[] = [
  {
    id: 'letter_1',
    title: 'The Feather Note',
    content: 'Left a white feather on the moss. "Someone might smile because of this."',
    locationName: 'Central Glade Path',
    x: 3000,
    y: 3100,
    zoneId: 'central_glade',
    unlocked: false,
  },
  {
    id: 'letter_2',
    title: 'Sunrise Walk',
    content: 'I walked early this morning as the dew sparkled. The forest was so quiet.',
    locationName: 'Central Glade Arch',
    x: 3200,
    y: 2800,
    zoneId: 'central_glade',
    unlocked: false,
  },
  {
    id: 'letter_3',
    title: 'Sunset Trace',
    content: 'I walked after sunset. Found the little drawing you left on the stone.',
    locationName: 'Flower Meadow Slope',
    x: 1400,
    y: 3000,
    zoneId: 'meadow',
    unlocked: false,
  },
  {
    id: 'letter_4',
    title: 'There\'s Always Tomorrow',
    content: 'Hope tomorrow treats you kindly. There is always tomorrow.',
    locationName: 'Lavender Patch',
    x: 1100,
    y: 3600,
    zoneId: 'meadow',
    unlocked: false,
  },
  {
    id: 'letter_5',
    title: 'The Rain Shelter',
    content: 'Listen to the rain under the canopy. It doesn\'t rush, yet it fills the whole forest.',
    locationName: 'Evergreen Canopy',
    x: 1300,
    y: 1400,
    zoneId: 'rain_bench',
    unlocked: false,
  },
  {
    id: 'letter_6',
    title: 'The Waiting Bench',
    content: 'Sitting here on the shelter bench during cancelled calls is not wasted time. It is remembering.',
    locationName: 'Rain Bench',
    x: 1400,
    y: 1200,
    zoneId: 'rain_bench',
    unlocked: false,
  },
  {
    id: 'letter_7',
    title: 'Coffee Tally Marks',
    content: 'Someone still owes someone coffee. 3 tally marks drawn on the counter.',
    locationName: 'Abandoned Kiosk',
    x: 4400,
    y: 3100,
    zoneId: 'coffee_corner',
    unlocked: false,
  },
  {
    id: 'letter_8',
    title: 'Warm Cups',
    content: 'Warm cups held in two hands on cold evenings. Coffee first. Everything else later.',
    locationName: 'Coffee Table',
    x: 4800,
    y: 3400,
    zoneId: 'coffee_corner',
    unlocked: false,
  },
  {
    id: 'letter_9',
    title: 'Lake Water Ripples',
    content: 'The lake holds reflections of everything that passes over it, without holding onto any of them.',
    locationName: 'Firefly Lake Shore',
    x: 4500,
    y: 1400,
    zoneId: 'lake',
    unlocked: false,
  },
  {
    id: 'letter_10',
    title: 'Tiny Moments',
    content: 'Whenever a firefly lands nearby, it replays a memory—not a grand one, just someone laughing.',
    locationName: 'Lake Pier Edge',
    x: 4900,
    y: 1100,
    zoneId: 'lake',
    unlocked: false,
  },
  {
    id: 'letter_11',
    title: 'Cauliflower Flower',
    content: 'A drawing of a cauliflower labeled "Rare Flower". An inside joke shared between two travelers.',
    locationName: 'Whisper Tree Bark',
    x: 3000,
    y: 1200,
    zoneId: 'whisper_tree',
    unlocked: false,
  },
  {
    id: 'letter_12',
    title: 'Unspoken Words',
    content: 'You don\'t have to explain everything to the world. Some thoughts belong only to you.',
    locationName: 'Whisper Tree Glade',
    x: 2700,
    y: 900,
    zoneId: 'whisper_tree',
    unlocked: false,
  },
  {
    id: 'letter_13',
    title: 'The Arcade Token',
    content: 'A shiny brass token from a 90s arcade machine for a game we planned to play.',
    locationName: 'Memory Trunk',
    x: 4500,
    y: 4600,
    zoneId: 'memory_hollow',
    unlocked: false,
  },
  {
    id: 'letter_14',
    title: 'The Leather Football',
    content: 'A scuffed leather football resting in Memory Hollow grass alongside unfinished sentences.',
    locationName: 'Old Notebook Page',
    x: 5100,
    y: 5000,
    zoneId: 'memory_hollow',
    unlocked: false,
  },
  {
    id: 'letter_15',
    title: 'Traces on Every Path',
    content: 'Maybe we never walked together. But every path I walked had signs that you had been there first.',
    locationName: 'Station Platform',
    x: 1400,
    y: 4800,
    zoneId: 'train_station',
    unlocked: false,
  },
];

// 3. 6 Playlist Tapes
export const INITIAL_TAPES: CassetteTapeEntity[] = [
  {
    id: 'tape_1',
    songTitle: 'Rainy Evening Piano',
    artist: 'Cozy Solitude',
    description: 'Soft, gentle piano keys that mimic raindrops on window glass.',
    x: 1700,
    y: 3300,
    zoneId: 'meadow',
    unlocked: false,
    spotifyQuery: 'rainy evening piano cozy ambient',
    albumArtColor: '#4338ca',
  },
  {
    id: 'tape_2',
    songTitle: 'Wind in the Pines',
    artist: 'Forest Whispers',
    description: 'A warm acoustic string melody layered with rustling leaves.',
    x: 1700,
    y: 1200,
    zoneId: 'rain_bench',
    unlocked: false,
    spotifyQuery: 'wind in the pines acoustic ambient',
    albumArtColor: '#15803d',
  },
  {
    id: 'tape_3',
    songTitle: 'Midnight Coffee',
    artist: 'Lo-Fi Traveler',
    description: 'Warm vinyl crackle with smooth guitar chords for quiet nights.',
    x: 4600,
    y: 3000,
    zoneId: 'coffee_corner',
    unlocked: false,
    spotifyQuery: 'midnight coffee lofi chill hop',
    albumArtColor: '#b45309',
  },
  {
    id: 'tape_4',
    songTitle: 'Reflections on Water',
    artist: 'Starlight Nocturne',
    description: 'Minimalist ambient pads evoking calm nighttime waters.',
    x: 4400,
    y: 1300,
    zoneId: 'lake',
    unlocked: false,
    spotifyQuery: 'reflections on water relaxing ambient',
    albumArtColor: '#0369a1',
  },
  {
    id: 'tape_5',
    songTitle: 'Echoes of the Ancient Tree',
    artist: 'Dreamcatcher',
    description: 'Ethereal bells and comforting harmony for deep reflection.',
    x: 3000,
    y: 800,
    zoneId: 'whisper_tree',
    unlocked: false,
    spotifyQuery: 'ethereal piano ambient peaceful',
    albumArtColor: '#6d28d9',
  },
  {
    id: 'tape_6',
    songTitle: 'Final Station Campfire',
    artist: 'Homecoming',
    description: 'A comforting acoustic song that marks the peaceful end of a journey.',
    x: 1600,
    y: 5200,
    zoneId: 'train_station',
    unlocked: false,
    spotifyQuery: 'peaceful acoustic campfire melody',
    albumArtColor: '#c2410c',
  },
];

// 4. Coffee Beans
export function generateCoffeeBeans(): CoffeeBeanEntity[] {
  const beans: CoffeeBeanEntity[] = [];
  for (let i = 1; i <= 10; i++) {
    beans.push({
      id: `bean_${i}`,
      x: 4200 + (i % 4) * 110 + Math.sin(i) * 30,
      y: 3000 + Math.floor(i / 4) * 90 + Math.cos(i) * 30,
      collected: false,
    });
  }
  return beans;
}

// 5. 10 Hidden Easter Eggs
export const EASTER_EGGS: EasterEggEntity[] = [
  {
    id: 'egg_1',
    name: 'My Lady',
    description: 'A tiny carved heart with the words "My Lady" inscribed into a mossy stone.',
    x: 2900,
    y: 2900,
    found: false,
    iconName: 'Heart',
  },
  {
    id: 'egg_2',
    name: 'Cauliflower Roast 🥦',
    description: 'A surprising little recipe card for roasted cauliflower left under a sunflower!',
    x: 2000,
    y: 3800,
    found: false,
    iconName: 'Utensils',
  },
  {
    id: 'egg_3',
    name: 'Shampoo in your eye 😂',
    description: 'A scribbled note complaining about getting shampoo in eyes while showering.',
    x: 1000,
    y: 1800,
    found: false,
    iconName: 'Smile',
  },
  {
    id: 'egg_4',
    name: 'Coffee Debt',
    description: 'A tally mark receipt showing 3 unpaid cappuccinos.',
    x: 4500,
    y: 3300,
    found: false,
    iconName: 'Coffee',
  },
  {
    id: 'egg_5',
    name: 'Knife Emoji Tree Carving 🔪',
    description: 'A tiny knife outline carved into the ancient bark of the Whisper Tree.',
    x: 3000,
    y: 1150,
    found: false,
    iconName: 'Carving',
  },
  {
    id: 'egg_6',
    name: 'Arcade Token',
    description: 'A shiny brass token from a 90s arcade machine.',
    x: 4800,
    y: 4500,
    found: false,
    iconName: 'Coins',
  },
  {
    id: 'egg_7',
    name: 'Old Passport',
    description: 'A well-traveled passport stamped with distant train stations.',
    x: 5200,
    y: 4900,
    found: false,
    iconName: 'Globe',
  },
  {
    id: 'egg_8',
    name: 'Germany Map & Cathedral Sketch',
    description: 'Hand-drawn map of Cologne Cathedral and ancient cobblestone streets.',
    x: 5000,
    y: 5300,
    found: false,
    iconName: 'MapPin',
  },
  {
    id: 'egg_9',
    name: 'Old Football',
    description: 'A slightly scuffed leather football resting in the tall grass.',
    x: 2000,
    y: 4600,
    found: false,
    iconName: 'Trophy',
  },
  {
    id: 'egg_10',
    name: 'Tiny Coffee Receipt',
    description: '"Some promises stay booked. Never overdo them."',
    x: 1200,
    y: 5200,
    found: false,
    iconName: 'Receipt',
  },
];

// 6. Interactive Points across 6000x6000px Open World
export const INTERACTIVE_POINTS: InteractivePoint[] = [
  {
    id: 'bench_rain',
    x: 1400,
    y: 1200,
    radius: 70,
    type: 'bench',
    label: 'Sit on Bench & Rest in Rain',
    zoneId: 'rain_bench',
  },
  {
    id: 'coffee_stand',
    x: 4400,
    y: 3100,
    radius: 80,
    type: 'coffee_stand',
    label: 'Inspect Coffee Stand & Exchange Beans',
    zoneId: 'coffee_corner',
  },
  {
    id: 'stone_lake',
    x: 4500,
    y: 1400,
    radius: 90,
    type: 'stone_skipping',
    label: 'Skip Stones across Lake',
    zoneId: 'lake',
  },
  {
    id: 'whisper_tree_main',
    x: 3000,
    y: 1100,
    radius: 100,
    type: 'whisper_tree',
    label: 'Write in Whisper Tree',
    zoneId: 'whisper_tree',
  },
  {
    id: 'cat_station',
    x: 1500,
    y: 4950,
    radius: 65,
    type: 'cat',
    label: 'Pet the Cozy Sleeping Cat',
    zoneId: 'train_station',
  },
  {
    id: 'birds_meadow',
    x: 1600,
    y: 3100,
    radius: 70,
    type: 'birds',
    label: 'Feed Bird Seeds',
    zoneId: 'meadow',
  },
  {
    id: 'campfire_ending',
    x: 1500,
    y: 5100,
    radius: 80,
    type: 'train_campfire',
    label: 'Sit by Campfire (Final Destination)',
    zoneId: 'train_station',
  },
];
