import type {
  CassetteTapeEntity,
  CoffeeBeanEntity,
  EasterEggEntity,
  FireflyEntity,
  InteractivePoint,
  LetterEntity,
  ZoneInfo,
} from '../types/game';

// 12 Open World Biomes across 10,000px × 10,000px Expanded Map Grid
export const ZONES: ZoneInfo[] = [
  {
    id: 'central_glade',
    name: 'Central Glade',
    minX: 3500,
    maxX: 6500,
    minY: 3500,
    maxY: 6500,
    description: 'A serene opening path at the heart of the forest surrounded by soft twilight.',
    ambientSound: 'forest',
  },
  {
    id: 'arcade_ruins',
    name: 'Arcade Ruins & Neon Shrine',
    minX: 500,
    maxX: 3500,
    minY: 500,
    maxY: 2500,
    description: 'An abandoned retro arcade among pine roots with a flickering CRT screen and brass tokens.',
    ambientSound: 'forest',
  },
  {
    id: 'rain_bench',
    name: 'Rain Canopy & Shelter',
    minX: 500,
    maxX: 3500,
    minY: 2500,
    maxY: 4500,
    description: 'A secluded wooden bench sheltered under evergreen leaves with peaceful rain.',
    ambientSound: 'rain',
  },
  {
    id: 'meadow',
    name: 'Flower Meadow & Windmill Hill',
    minX: 500,
    maxX: 3500,
    minY: 4500,
    maxY: 6500,
    description: 'Fields of glowing lavender, gold wildflowers, and gentle hilltop breezes.',
    ambientSound: 'wind',
  },
  {
    id: 'cauliflower_ridge',
    name: 'Cauliflower Ridge & Sunset Bench',
    minX: 500,
    maxX: 3500,
    minY: 6500,
    maxY: 9500,
    description: 'Golden cauliflower blooms swaying on high cliffs overlooking the sweeping sunset horizon.',
    ambientSound: 'wind',
  },
  {
    id: 'whisper_tree',
    name: 'Whisper Tree Glade',
    minX: 3500,
    maxX: 6500,
    minY: 500,
    maxY: 3500,
    description: 'The ancient glowing heart of the forest. The tree listens closely, but never answers.',
    ambientSound: 'wind',
  },
  {
    id: 'starlight_bridge',
    name: 'Starlight Bridge & Waterfalls',
    minX: 6500,
    maxX: 9500,
    minY: 500,
    maxY: 2500,
    description: 'A rustic wooden bridge spanning crystal waterfalls and bioluminescent lotus pools.',
    ambientSound: 'stream',
  },
  {
    id: 'lake',
    name: 'Firefly Lake & Starlight Pier',
    minX: 6500,
    maxX: 9500,
    minY: 2500,
    maxY: 5500,
    description: 'Starlight and fireflies reflect off calm lake waters. Smooth stones line the shore.',
    ambientSound: 'stream',
  },
  {
    id: 'coffee_corner',
    name: 'Coffee Corner Kiosk',
    minX: 6500,
    maxX: 9500,
    minY: 4000,
    maxY: 6500,
    description: 'A small abandoned coffee stand left in the forest. Warm aromas linger.',
    ambientSound: 'forest',
  },
  {
    id: 'memory_hollow',
    name: 'Memory Hollow Roots',
    minX: 6500,
    maxX: 9500,
    minY: 6500,
    maxY: 9500,
    description: 'Forgotten keepsakes rest among mossy roots: letters, old photos, and cassette tapes.',
    ambientSound: 'forest',
  },
  {
    id: 'observatory',
    name: 'Forgotten Telescope Observatory',
    minX: 3500,
    maxX: 6500,
    minY: 6500,
    maxY: 9500,
    description: 'An ancient stone observatory tower under starlight where travelers watched constellations.',
    ambientSound: 'wind',
  },
  {
    id: 'train_station',
    name: 'Old Train Station Campfire',
    minX: 1000,
    maxX: 4000,
    minY: 8500,
    maxY: 9800,
    description: 'A rustic abandoned station platform with a small crackling campfire.',
    ambientSound: 'station',
  },
];

// Generate 80 Glowing Fireflies scattered across 10,000px × 10,000px space
export function generateFireflies(): FireflyEntity[] {
  const fireflies: FireflyEntity[] = [];
  const colors = ['#fef08a', '#fde047', '#fed7aa', '#ddd6fe', '#bae6fd', '#f472b6'];

  for (let i = 1; i <= 80; i++) {
    const angle = i * 0.42;
    const r = 400 + i * 115;
    const baseX = 5000 + Math.cos(angle) * r;
    const baseY = 5000 + Math.sin(angle) * r;

    const clampedX = Math.max(300, Math.min(9700, baseX));
    const clampedY = Math.max(300, Math.min(9700, baseY));

    const zone = ZONES.find(
      (z) => clampedX >= z.minX && clampedX <= z.maxX && clampedY >= z.minY && clampedY <= z.maxY
    ) || ZONES[0];

    fireflies.push({
      id: `firefly_${i}`,
      x: clampedX,
      y: clampedY,
      baseX: clampedX,
      baseY: clampedY,
      collected: false,
      color: colors[i % colors.length],
      radius: 4.0 + (i % 3),
      pulsePhase: Math.random() * Math.PI * 2,
      floatAngle: Math.random() * Math.PI * 2,
      speed: 0.5 + Math.random() * 0.8,
      zoneId: zone.id,
    });
  }

  return fireflies;
}

// 10 Memory Pages scattered across 10,000px map
export const INITIAL_LETTERS: LetterEntity[] = [
  {
    id: 'letter_1',
    title: 'Tiny Coffee Mug',
    content: 'One coffee became two. Then four. Then somehow... nobody remembered who owed whom anymore.',
    locationName: 'Coffee Corner Kiosk',
    x: 8000,
    y: 4800,
    zoneId: 'coffee_corner',
    unlocked: false,
  },
  {
    id: 'letter_2',
    title: 'Old Arcade Cabinet',
    content: 'The high score was never important. Laughing because somebody cheated was.',
    locationName: 'Arcade Ruins Shrine',
    x: 2000,
    y: 1500,
    zoneId: 'arcade_ruins',
    unlocked: false,
  },
  {
    id: 'letter_3',
    title: 'Football Under Tree',
    content: 'Practice finished. Boots removed. Somebody was still waiting.',
    locationName: 'Memory Hollow Roots',
    x: 8000,
    y: 7800,
    zoneId: 'memory_hollow',
    unlocked: false,
  },
  {
    id: 'letter_4',
    title: 'Cauliflower Flower',
    content: 'Not every flower needs petals. 😂',
    locationName: 'Cauliflower Ridge Bench',
    x: 2000,
    y: 8200,
    zoneId: 'cauliflower_ridge',
    unlocked: false,
  },
  {
    id: 'letter_5',
    title: 'Notebook Page',
    content: '"Let\'s learn together."',
    locationName: 'Flower Meadow Slope',
    x: 2000,
    y: 4800,
    zoneId: 'meadow',
    unlocked: false,
  },
  {
    id: 'letter_6',
    title: 'Empty Rain Bench',
    content: 'Today\'s slot expired. There\'s always tomorrow.',
    locationName: 'Rain Canopy Shelter',
    x: 2000,
    y: 2800,
    zoneId: 'rain_bench',
    unlocked: false,
  },
  {
    id: 'letter_7',
    title: 'Tiny Chocolate',
    content: 'Someone chose only chocolate. Someone forced them to choose a book too.',
    locationName: 'Observatory Tower',
    x: 5000,
    y: 8500,
    zoneId: 'observatory',
    unlocked: false,
  },
  {
    id: 'letter_8',
    title: 'Motivational Book',
    content: 'Somehow... they both picked the same one.',
    locationName: 'Starlight Bridge',
    x: 8000,
    y: 1500,
    zoneId: 'starlight_bridge',
    unlocked: false,
  },
  {
    id: 'letter_9',
    title: 'Glowing Pen',
    content: 'Nobody knew whose pen it really was. 😂',
    locationName: 'Whisper Tree Bark',
    x: 5000,
    y: 2000,
    zoneId: 'whisper_tree',
    unlocked: false,
  },
  {
    id: 'letter_10',
    title: 'Tiny Lantern',
    content: 'Some stories are easier to tell in dreams.',
    locationName: 'Central Glade Path',
    x: 5000,
    y: 5000,
    zoneId: 'central_glade',
    unlocked: false,
  },
];

// 6 Playlist Tapes
export const INITIAL_TAPES: CassetteTapeEntity[] = [
  {
    id: 'tape_1',
    songTitle: 'Rainy Evening Piano',
    artist: 'Cozy Solitude',
    description: 'Soft, gentle piano keys that mimic raindrops on window glass.',
    x: 2000,
    y: 4800,
    zoneId: 'meadow',
    unlocked: false,
    spotifyQuery: 'rainy evening piano cozy ambient',
    albumArtColor: '#4338ca',
  },
  {
    id: 'tape_2',
    songTitle: 'Wind in the Pines',
    artist: 'Forest Whispers',
    description: 'A warm acoustic string melody layered with rustling leaves.',
    x: 2000,
    y: 2800,
    zoneId: 'rain_bench',
    unlocked: false,
    spotifyQuery: 'wind in the pines acoustic ambient',
    albumArtColor: '#15803d',
  },
  {
    id: 'tape_3',
    songTitle: 'Midnight Coffee',
    artist: 'Lo-Fi Traveler',
    description: 'Warm vinyl crackle with smooth guitar chords for quiet nights.',
    x: 8000,
    y: 4800,
    zoneId: 'coffee_corner',
    unlocked: false,
    spotifyQuery: 'midnight coffee lofi chill hop',
    albumArtColor: '#b45309',
  },
  {
    id: 'tape_4',
    songTitle: 'Reflections on Water',
    artist: 'Starlight Nocturne',
    description: 'Minimalist ambient pads evoking calm nighttime waters.',
    x: 8000,
    y: 3500,
    zoneId: 'lake',
    unlocked: false,
    spotifyQuery: 'reflections on water relaxing ambient',
    albumArtColor: '#0369a1',
  },
  {
    id: 'tape_5',
    songTitle: 'Echoes of the Ancient Tree',
    artist: 'Dreamcatcher',
    description: 'Ethereal bells and comforting harmony for deep reflection.',
    x: 5000,
    y: 2000,
    zoneId: 'whisper_tree',
    unlocked: false,
    spotifyQuery: 'ethereal piano ambient peaceful',
    albumArtColor: '#6d28d9',
  },
  {
    id: 'tape_6',
    songTitle: 'Final Station Campfire',
    artist: 'Homecoming',
    description: 'A comforting acoustic song that marks the peaceful end of a journey.',
    x: 2000,
    y: 9200,
    zoneId: 'train_station',
    unlocked: false,
    spotifyQuery: 'peaceful acoustic campfire melody',
    albumArtColor: '#c2410c',
  },
];

// Coffee Beans Generator
export function generateCoffeeBeans(): CoffeeBeanEntity[] {
  const beans: CoffeeBeanEntity[] = [];
  for (let i = 1; i <= 15; i++) {
    beans.push({
      id: `bean_${i}`,
      x: 7500 + (i % 5) * 160 + Math.sin(i) * 40,
      y: 4500 + Math.floor(i / 5) * 140 + Math.cos(i) * 40,
      collected: false,
    });
  }
  return beans;
}

// 12 Hidden Easter Eggs
export const EASTER_EGGS: EasterEggEntity[] = [
  {
    id: 'egg_1',
    name: 'My Lady',
    description: 'A tiny carved heart with the words "My Lady" inscribed into a mossy stone.',
    x: 4800,
    y: 4800,
    found: false,
    iconName: 'Heart',
  },
  {
    id: 'egg_2',
    name: 'Cauliflower Roast 🥦',
    description: 'A surprising little recipe card for roasted cauliflower left under a sunflower!',
    x: 2000,
    y: 8200,
    found: false,
    iconName: 'Utensils',
  },
  {
    id: 'egg_3',
    name: 'Shampoo in your eye 😂',
    description: 'A scribbled note complaining about getting shampoo in eyes while showering.',
    x: 1800,
    y: 3200,
    found: false,
    iconName: 'Smile',
  },
  {
    id: 'egg_4',
    name: 'Coffee Debt',
    description: 'A tally mark receipt showing 3 unpaid cappuccinos.',
    x: 8100,
    y: 5000,
    found: false,
    iconName: 'Coffee',
  },
  {
    id: 'egg_5',
    name: 'Knife Emoji Tree Carving 🔪',
    description: 'A tiny knife outline carved into the ancient bark of the Whisper Tree.',
    x: 5000,
    y: 2000,
    found: false,
    iconName: 'Carving',
  },
  {
    id: 'egg_6',
    name: 'Arcade Token',
    description: 'A shiny brass token from a 90s arcade machine.',
    x: 2000,
    y: 1500,
    found: false,
    iconName: 'Coins',
  },
  {
    id: 'egg_7',
    name: 'Old Passport',
    description: 'A well-traveled passport stamped with distant train stations.',
    x: 8200,
    y: 8200,
    found: false,
    iconName: 'Globe',
  },
  {
    id: 'egg_8',
    name: 'Germany Map & Cathedral Sketch',
    description: 'Hand-drawn map of Cologne Cathedral and ancient cobblestone streets.',
    x: 8500,
    y: 8500,
    found: false,
    iconName: 'MapPin',
  },
  {
    id: 'egg_9',
    name: 'Old Football',
    description: 'A slightly scuffed leather football resting in the tall grass.',
    x: 8000,
    y: 7800,
    found: false,
    iconName: 'Trophy',
  },
  {
    id: 'egg_10',
    name: 'Starlight Telescope Lens',
    description: 'A brass telescope lens pointing toward the northern star.',
    x: 5000,
    y: 8500,
    found: false,
    iconName: 'Eye',
  },
  {
    id: 'egg_11',
    name: 'Waterfall Lotus Flower',
    description: 'A glowing lotus flower floating peacefully at the base of the waterfall.',
    x: 8000,
    y: 1500,
    found: false,
    iconName: 'Sparkles',
  },
  {
    id: 'egg_12',
    name: 'Tiny Coffee Receipt',
    description: '"Some promises stay booked. Never overdo them."',
    x: 2000,
    y: 9200,
    found: false,
    iconName: 'Receipt',
  },
];

// 11 Interactive Points across 10,000px × 10,000px Open World
export const INTERACTIVE_POINTS: InteractivePoint[] = [
  {
    id: 'bench_rain',
    x: 2000,
    y: 2800,
    radius: 90,
    type: 'bench',
    label: 'Sit on Bench & Rest in Rain',
    zoneId: 'rain_bench',
  },
  {
    id: 'arcade_machine_spot',
    x: 2000,
    y: 1500,
    radius: 90,
    type: 'coffee_stand',
    label: 'Inspect Retro Arcade Machine & Insert Token',
    zoneId: 'arcade_ruins',
  },
  {
    id: 'coffee_stand',
    x: 8000,
    y: 4800,
    radius: 90,
    type: 'coffee_stand',
    label: 'Inspect Coffee Stand & Exchange Beans',
    zoneId: 'coffee_corner',
  },
  {
    id: 'stone_lake',
    x: 8000,
    y: 3500,
    radius: 100,
    type: 'stone_skipping',
    label: 'Skip Stones across Lake',
    zoneId: 'lake',
  },
  {
    id: 'starlight_bridge_spot',
    x: 8000,
    y: 1500,
    radius: 90,
    type: 'stone_skipping',
    label: 'Look off Starlight Waterfall Bridge',
    zoneId: 'starlight_bridge',
  },
  {
    id: 'whisper_tree_main',
    x: 5000,
    y: 2000,
    radius: 110,
    type: 'whisper_tree',
    label: 'Some words are not ready for another heart. Leave them here. The forest keeps promises.',
    zoneId: 'whisper_tree',
  },
  {
    id: 'cauliflower_bench_spot',
    x: 2000,
    y: 8200,
    radius: 90,
    type: 'bench',
    label: 'Sit on Sunset Ridge Bench',
    zoneId: 'cauliflower_ridge',
  },
  {
    id: 'observatory_spot',
    x: 5000,
    y: 8500,
    radius: 100,
    type: 'telescope',
    label: 'Gaze through Starlight Telescope at Constellations',
    zoneId: 'observatory',
  },
  {
    id: 'cat_station',
    x: 2000,
    y: 9200,
    radius: 75,
    type: 'cat',
    label: 'Pet the Cozy Sleeping Cat',
    zoneId: 'train_station',
  },
  {
    id: 'birds_meadow',
    x: 2000,
    y: 4800,
    radius: 80,
    type: 'birds',
    label: 'Feed Bird Seeds',
    zoneId: 'meadow',
  },
  {
    id: 'campfire_ending',
    x: 2000,
    y: 9200,
    radius: 90,
    type: 'train_campfire',
    label: 'Sit by Campfire (Final Destination)',
    zoneId: 'train_station',
  },
];
